FROM openjdk:8-jdk-alpine
COPY .  /opt/jshERP-boot/
WORKDIR /opt/jshERP-boot/
EXPOSE 9999
ENTRYPOINT ["java", "-server", "-Xms128m", "-Xmx320m", "-XX:PermSize=128M", "-XX:MaxPermSize=256M", "-Dspring.pid.fail-on-write-error=true", "-jar","lib/jshERP.jar"]
